### ISSUE TITLE
Chrome integration such as provided by Grammarly?

### ISSUE THREAD

**Issue by orschiro** [languagetool-org/languagetool-browser-addon#104]
Dear all, 

I have both installed [Grammarly](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen) and the LanguageTool.

However, I find myself almost never using the LanguageTool because it does not have the same seamless integration into my composing window as Grammarly does. 

Against this background, I simply forget to open LanguageTool using the shortcut or clicking on its icon. However, I would really like to use it more. 

This brings me to my question: 

Would it be possible to provide a similar integration as Grammarly provides it?

Yours,

Robert

![image](https://cloud.githubusercontent.com/assets/170947/24320037/ccad50aa-112c-11e7-960b-311a7afd2742.png)

![image](https://cloud.githubusercontent.com/assets/170947/24320062/57623076-112d-11e7-9aae-5dbd11bedffe.png)

**Comment by danielnaber** [comment]
There's no support for this from the browser, so everything needs to be done on the level of modifying the DOM. This is difficult and fragile. So it's somehow possible, but nobody seems to be working on this. Also see #98.

**Comment by orschiro** [comment]
I see. Thank you, @danielnaber.

It might not be missing for other users then if nobody is interested in working on this. 

Well, let us see. Maybe one day then. :-)

**Comment by danielnaber** [comment]
I'm closing this as it's basically what #98 suggests.
