### ISSUE TITLE
Keyboard shortcut does not work on Vivaldi browser

### ISSUE THREAD

**Issue by DanielChesters** [languagetool-org/languagetool-browser-addon#107]
Hi,

I use the chrome extension on last stable version of Vivaldi and the default keyboard shortcut do nothing but I can use extension via icon extension.

Thanks

**Comment by danielnaber** [comment]
Thanks for the report - could you check if it helps to re-set the shortcut?

**Comment by DanielChesters** [comment]
Same problem when I set shortcut to “Control + Shift + Y” (for example)

**Comment by danielnaber** [comment]
In that case, I'd guess it's more of a Vivaldi issue. Do shortcuts work for other extensions for you?

**Comment by DanielChesters** [comment]
Some extensions, like Save to Pocket, have functional keyboard shortcut but it is managed by extension itself, the others, like LanguageTool or LastPass, don't but it is managed by “Vivaldi”.

**Comment by danielnaber** [comment]
We specify the shortcut here: https://github.com/languagetool-org/languagetool-browser-addon/blob/master/webextension/manifest.json#L44 - maybe you could report this as an issue to Vivaldi.

**Comment by danielnaber** [comment]
Closing as it seems to be a Vivaldi issue.
