### ISSUE TITLE
keyboard-only usage of add-on

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-browser-addon#109]
Idea: when the popup opens, it should be possible to use cursor keys to navigate suggestions and apply them with the Return key. Cursor up/down should go to previous/next error, cursor right/left should switch between different suggestions of the current error. There needs to be some highlighting so the user can see where the "cursor" currently is.

Cursor right/left should also allow user to navigate to the "turn off rule" and "add to dictionary" icon.

Source: http://forum.languagetool.org/t/no-mouse-needed-firefox-addon-feature-would-be-great/1997

**Comment by mathroc** [comment]
I’d like to also be able to change the detected language with the keyboard

**Comment by danielnaber** [comment]
Hi @mathroc, does it often happen to you that the detected languages isn't correct? If so, what language are you working with? Are the text you're checking very short?

**Comment by mathroc** [comment]
@danielnaber I just installed the add-on so this was mostly on tests, incorrect detections happened only for short texts (in french)

Maybe something better would be an option to disable some languages ?

**Comment by danielnaber** [comment]
> Maybe something better would be an option to disable some languages ?

I think that's a good approach, or maybe only detect languages from a limited set. But we'd need a clever and non-obtrusive UI for that... I wouldn't want to hide this in the configuration dialog.

**Comment by danielnaber** [comment]
I'm closing this, as it's mostly done. Doesn't work on Firefox yet, see #111.
