### ISSUE TITLE
Doesn't work with Collabora Office

### ISSUE THREAD

**Issue by Jab2870** [languagetool-org/languagetool-browser-addon#115]
I use [Collobora Office](https://www.collaboraoffice.com/) with nextcloud for online document editing. Unfortunately, the chromium browser extension doesn't pick up any spelling corrections.

**Comment by danielnaber** [comment]
Thanks for your bug report. This is similar to Google Docs, which also needs its own add-on: LanguageTool needs plain text, but while a standard HTML page contains the text you see on the screen, the Collabora Office page doesn't (or if it does, it's hidden really well). So we'd need to write a new add-on for Collabora Office.

As a first fix, we should at least show a better message than just "no errors found" (when we actually haven't found *text* at all).

**Comment by Jab2870** [comment]
Thanks for the feedback. As far as I know, Collabora doesn't support plugins which is why I assumed a browser extension was more possible.

I might soon make the switch to [Only Office](https://www.onlyoffice.com/), do you know if this would have the same problem? I know that Only Office does support plugins so it might be possible for a plugin to be used for this.

**Comment by danielnaber** [comment]
I don't know about Only Office, you'll have to try whether it works.

**Comment by danielnaber** [comment]
The error message will be improved with the next release of the add-on. Other than that, I guess there's not much we can do (with add-ons not being supported, as you mentioned), so I'm closing this.
