### ISSUE TITLE
The position of the LT icon is not consistent

### ISSUE THREAD

**Issue by nopepper** [languagetool-org/languagetool-browser-addon#120]
Examples: 
- [x] https://community.languagetool.org/ruleEditor/expert (https://i.imgur.com/57Ff7rB.png)
- [x] https://regex101.com/ (https://i.imgur.com/KvZl8MP.png)
- [x] Gmail (when replying) (https://i.imgur.com/mSNyueB.png)

**Comment by janschreiber** [comment]
It looks weird on Google Spreadsheets:
![screenshot-2017-9-19 arbeitszeiten jan lt premium](https://user-images.githubusercontent.com/4381288/30606708-e3817f0e-9d72-11e7-9776-2019995b873e.png)
