### ISSUE TITLE
Too many far-fetched suggestions for spelling errors

### ISSUE THREAD

**Issue by nopepper** [languagetool-org/languagetool-browser-addon#121]
Example: the German sentence: "Ich bin zeuhause", where "zuhause" is the correct spelling -> https://i.imgur.com/qCpDWgY.png
Another example: https://i.imgur.com/Ji32X35.png
It might also be a good idea not to give uppercase suggestions for lowercase words and vice versa, and to sort suggestions by their similarity to the original word.

**Comment by danielnaber** [comment]
As this is not specific to the add-on, please open this issue at https://github.com/languagetool-org/languagetool
