### ISSUE TITLE
Offer localisation support for Dutch

### ISSUE THREAD

**Issue by PanderMusubi** [languagetool-org/languagetool-browser-addon#135]
Please add Dutch (nl) to the localisation at https://github.com/languagetool-org/languagetool-browser-addon/tree/master/webextension/_locales (via Transifex e.g.)

**Comment by danielnaber** [comment]
Done, but Transifex may take up to 24 hours to see the new file. Please let me know here when it's translated.

**Comment by PanderMusubi** [comment]
Done. I have spend over 4 hours reviewing also most of the already translated other Dutch LT sources at Transifex. You can probably see which other components also need updating for Dutch localisation.

**Comment by danielnaber** [comment]
Thanks, Dutch will be part of the next release.

**Comment by danielnaber** [comment]
We currently have a phase where we make updates regularly (like today), would be great if you could keep the translation up-to-date. Usually it's just 1-3 sentences per day.
