### ISSUE TITLE
Add-on gone from Chromium after reboot (Lubuntu 16.04)

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool-browser-addon#163]
**Specs:**
Kernel: Linux 4.4.0-97-generic (i686)
Compiled: 120-Ubuntu SMP Tue Sep 19 17:27:07 UTC 2017
Distribution: Ubuntu 16.04.3 LTS
Chromium: Version 61.0.3163.100 (Official Build) Built on Ubuntu, running on Ubuntu 16.04 (32-Bit)
LT Add-on: Version 1.0.30

**Problem:**
After rebooting the OS, the LT add-on is removed from Chromium.

**Comment by danielnaber** [comment]
1.0.30 is a test version, please try with the version from the Google Web Store.

**Comment by janschreiber** [comment]
With LT add-on version 1.0.26 the problem does not occur.
