### ISSUE TITLE
Missing icon on sourceforge

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-browser-addon#170]
See bug report at https://forum.languagetool.org/t/test-of-firefox-add-on-update/2258/5

**Comment by jellydn** [comment]
Hi Daniel, 

Refer to my screenshot, the spellcheck is `false`. That's working as design. The marker won't show on UI in this case. Thanks.

![screen shot 2017-10-25 at 10 23 47](https://user-images.githubusercontent.com/870029/31979020-b15f3f6c-b96e-11e7-869a-e2e371c4eefb.png)
