### ISSUE TITLE
In local mode addon doesn't work

### ISSUE THREAD

**Issue by maxtar** [languagetool-org/languagetool-browser-addon#175]
I have LanguageTool-3.9. Addon version 1.0.28.
When I try change URL to `http://localhost:8081/v2` and press save, I've got "This URL is not valid" error.

**Comment by danielnaber** [comment]
Thanks for the report, version 1.0.29 fixes this (released a few minutes ago).

**Comment by maxtar** [comment]
Thanx! It's works!
