### ISSUE TITLE
Addon has no settings disabling popup in textarea.

### ISSUE THREAD

**Issue by maxtar** [languagetool-org/languagetool-browser-addon#177]
I couldn't disable blue circle in right bottom corner of text area. It doesn't useful. Especially in small areas.

**Comment by danielnaber** [comment]
Hover over the icon, the click the left icon to turn off the add-on for this domain:

![hover](https://user-images.githubusercontent.com/857004/32329756-393b424e-bfde-11e7-8359-5677ae01c29e.png)

**Comment by maxtar** [comment]
@danielnaber I want to disable it on all domains. How I can do it? I prefer use `ctrl+shift+space` hotkey or press button on tool panel.

**Comment by danielnaber** [comment]
De-select "Auto-check on all domains by default" in the add-on settings (Tools -> Addons).

**Comment by maxtar** [comment]
@danielnaber I have de-selected it.
![default](https://user-images.githubusercontent.com/10290098/32330174-5e716630-bff0-11e7-9293-b5d7e1a036ad.png)

**Comment by danielnaber** [comment]
Now I see - turning off the blue icon on all domains is not possible.

**Comment by maxtar** [comment]
@danielnaber Could you add this setting?
