### ISSUE TITLE
Ignore parts of texts

### ISSUE THREAD

**Issue by freddie-freeloader** [languagetool-org/languagetool-browser-addon#189]
Hey!

If I write text that includes emojis (written in GitHub-flavored Markdown as e.g. `:slight_smile:`), they get rejected by LanguageTool.

Is there a way to configure a regex, for sequences that should be ignored by the spellchecker? This would be also handy for inline code snippets and such. :slightly_smiling_face:

**Comment by danielnaber** [comment]
Maybe this, not tested:

```
    <rule name="emoji" id="EMOJI">
        <pattern>
            <token>:</token>
            <token spacebefore="no" regexp="yes">slight_smile|others...</token>
            <token spacebefore="no">:</token>
        </pattern>
        <disambig action="ignore_spelling"/>
    </rule>
```

**Comment by freddie-freeloader** [comment]
After a little bit of research, I still not quite sure where to find or place the `disambiguation.xml`.
Is there any documentation I am missing?

**Comment by danielnaber** [comment]
It's a server-side file, if you download the ZIP from languagetool.org, it will be at `./org/languagetool/resource/en/disambiguation.xml` (for English).

**Comment by freddie-freeloader** [comment]
Do I understand correctly, that this option cannot be set on the client-side? :slightly_smiling_face:

**Comment by danielnaber** [comment]
That's right, it needs to be set on the server side. On the client-side you can only activate/deactivate rules.
