### ISSUE TITLE
auto-remember variant selection

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-browser-addon#190]
When the user manually selects e.g. British English (because en-US has been detected), offer to make that the default with a single click. I.e. the effect when the user clicks on the link should be the same as visiting the options dialog and setting en-GB as default for English.

**Comment by danielnaber** [comment]
More explanation: When user selects a different variant here:

![lang-select](https://user-images.githubusercontent.com/857004/33941356-a2892e56-e012-11e7-863d-bbee26afd839.png)

The check is run again - that works already. But if user selects en-GB, there's a good chance they *always* want British English. So after the check is run again with en-GB, a link should appear below the language drop-down that says "*Click here* to make English (British)" your default variant.". And if user clicks on the "click here", en-GB will be default, just as if the user had visited the configuration dialog and set en-GB as the variant for English.

Note: this is only about variants. Like en-US was detected, but user wants en-GB. Then en-GB should be offered as default. If en was detected but user switched to fr -> not relevant for this issue.

**Comment by danielnaber** [comment]
@seleznevStas : One small usability issue you can test with this text: `This is Bsritish English text - colour`

1. en-US is default
2. check the text -> 2 errors
3. switch manually to en-GB -> 1 error left
4. click the new link to make en-GB default -> 1 error left
5. click the suggestion for the error to fix `Bsritish` to `British`
6. it works, but it will offer the new link again, even though en-GB is already the new default

**Comment by seleznevStas** [comment]
It's happened because popup is reloaded and values in preferredVariants are wrong (not match with actual).
