### ISSUE TITLE
Bad design and bug in the pop-up on Firefox Quantum

### ISSUE THREAD

**Issue by gusbemacbe** [languagetool-org/languagetool-browser-addon#191]
Hello!

### Description

In the figure 1, there is a bad design in the pop-up that is at the upper right corner on Firefox Quantum, see:

![Figure 1](https://user-images.githubusercontent.com/2257024/33520960-01901f5a-d7ac-11e7-90f5-a8076bfbea52.png)

And in the figure 2, after removing and reinstalling the extension, the pop-up appears entirely white and doesn't detect the selected text. And the word 'varificar' is wrong. The correct is 'verificar' in both Brazilian and European Portuguese. 

![screen shot 2017-12-02 at 21 58 30](https://user-images.githubusercontent.com/2257024/33520974-49542264-d7ac-11e7-876b-35b9a92177da.png)

The extension title on the expanded menu isn't named 'LanguageTool', but 'Varificar  a seleção e atualou...'. 

### Version

**OS:** macOS 10.13.1 High Sierra
**Browser:** Firefox Developer Edition (Firefox Quantum) 58.0

**Comment by danielnaber** [comment]
Thanks for the report, I cannot reproduce it though. Are you using a Firefox theme? @TiagoSantos81 could you check the "varificar" bug?

**Comment by TiagoSantos81** [comment]
https://www.transifex.com/dnaber/languagetool/translate/#pt_BR/chrome-extension/65258211?qt=varificar

@MatheusPoletto That is a pt-BR error.

**Comment by gusbemacbe** [comment]
@danielnaber, Tiago is WRONG. Tiago closed only for the orthography?! I uninstalled and reinstalled, the design continues the same.

I am a default dark native theme of Firefox.

**Comment by danielnaber** [comment]
> I uninstalled and reinstalled, the design continues the same.

Please try if this also happens when LT isn't hidden behind the ">>" button but directly in the toolbar. Anyway, FF 58 is a  beta release and this may be a bug that might be fixed until release. I cannot reproduce it, neither on FF 57, nor on FF 58.

**Comment by gusbemacbe** [comment]
I unhid the extension from the expanded button and the design is different and normal now. Then the problem is in the expanded menu.
