### ISSUE TITLE
Feature: Quotation Marks

### ISSUE THREAD

**Issue by marcobiedermann** [languagetool-org/languagetool-browser-addon#197]
Really nice extension, good job.
I think a nice addition would be to support the proper quotation marks respecting the language:

### German Quotation Marks
```
„…“
‚…‘
»…«
›…‹
```

### English Quotation Marks
```
“…”
‘…’
```

### French Quotation Marks
```
« … »
```

**Comment by danielnaber** [comment]
Actually, LanguageTool has a rule for that, but it's turned off by default. See the link at the bottom you should get when you use the quotation marks (`"like this"`) that are not quite correct:

![bildschirmfoto vom 2017-12-12 12-12-34](https://user-images.githubusercontent.com/857004/33881720-f27177f8-df35-11e7-810a-791264f6ab81.png)

**Comment by marcobiedermann** [comment]
Uhhh, nice. I might have overlooked it. Thank you @danielnaber
