### ISSUE TITLE
Addon is reason slow down of firefox at the twitter.com

### ISSUE THREAD

**Issue by dimahetman** [languagetool-org/languagetool-browser-addon#207]
after several seconds since  twitter.com was opened firefox was freezen two times by several seconds with opened warning panel about it.
firefox 58.0.1 (64 bit) for
Ubuntu 16.04.3 LTS

**Comment by danielnaber** [comment]
Thanks for the report, can you reproduce this behavior? I'm using the same browser and OS and it works for me. Are you using the current version of the add-on?

**Comment by dimahetman** [comment]
I can send a light screencast.

**Comment by dimahetman** [comment]
add after my nickname "@" gmail domain = is my e-mail

**Comment by dimahetman** [comment]
LanguageTool version is 1.0.34

**Comment by danielnaber** [comment]
> I can send a light screencast.

Please do.

**Comment by dimahetman** [comment]
[Uploading Скрынкаст, 02.02.2018 00:03:43.webm.zip…]()
in the screencast, I did not have time to open Twitter for the second time, but the browser reported a slowdown on a blank page after addon was switch on

**Comment by dimahetman** [comment]
there is a possibility that this is due to the combination of my addons

**Comment by danielnaber** [comment]
Your attachment didn't quite make it to github it seems, the link is broken.

> there is a possibility that this is due to the combination of my addons

Maybe, could you check it by turning off (you don't need to deinstall) other add-ons?

**Comment by dimahetman** [comment]
experimentally found that together, work, badly only, languegetool and mate translate, other addons never mind. thank you

**Comment by danielnaber** [comment]
So I understand this issue only happens when you have "Make translate" installed at the same time?

**Comment by danielnaber** [comment]
Closing, as there was no further feedback.
