### ISSUE TITLE
does not apply corrections in Wordpress

### ISSUE THREAD

**Issue by SirLouen** [languagetool-org/languagetool-browser-addon#213]
I’m using this plugin in Wordpress editor (self-hosted), it does recognize the wrong words, but when I click on the right word to switch it for the wrong word within the text, it doesn’t do anything
Tried using both Chrome and Firefox addons

**Comment by jaumeortola** [comment]
I can confirm this issue. As WordPress is so popular, it would be nice to fix it. 

The WordPress editor is a "a modified version of TinyMCE". 

The error you can see in the console when trying to replace a word with a suggestion is this:

```
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'tagName' of undefined
    at isSimpleInput (chrome-extension://oldceeleldhonbafppcapldpdifcinji/cs/contentscript.js:196:14)
    at applyCorrection (chrome-extension://oldceeleldhonbafppcapldpdifcinji/cs/contentscript.js:174:9)
    at handleRequest (chrome-extension://oldceeleldhonbafppcapldpdifcinji/cs/contentscript.js:42:9)
```

**Comment by jaumeortola** [comment]
@danielnaber Have you any hint to fix this issue?

**Comment by danielnaber** [comment]
The update for Chrome will be online in about 60 minutes. To make sure you get the new version, you need to uninstall and re-install the add-on. The update for Firefox will probably follow later this week.

**Comment by danielnaber** [comment]
It works for me now (tested with Chrome). Could you provide a screenshot? Which site are you testing on?

**Comment by danielnaber** [comment]
Can you try on wordpress.com? That's where I have tested. Or could you create a test account for me in your WordPress?

**Comment by jaumeortola** [comment]
I see. On wordpress.com they are using the new editor (Gutenberg) instead of TinyMCE. It will become the default editor soon on WordPress. It also works for me.
 
I have created a test account for you on a site with the old editor.

**Comment by danielnaber** [comment]
Mhh, I still cannot reproduce the problem with the old editor. Are you absolutely sure you're using 1.0.37?

**Comment by jaumeortola** [comment]
You are right. It's fixed. Probably I needed to restart Chrome. Thank you very much.

**Comment by SirLouen** [comment]
I've installed latest version + restarted the PC and still this error:

Error in event handler for runtime.onMessage: TypeError: Cannot read property 'hasAttribute' of undefined
    at applyCorrection (chrome-extension://oldceeleldhonbafppcapldpdifcinji/cs/contentscript.js:177:20)
    at handleRequest (chrome-extension://oldceeleldhonbafppcapldpdifcinji/cs/contentscript.js:44:9)

**Comment by danielnaber** [comment]
@SirLouen Where exactly (on which URL and which version of WordPress) do you get this error? What version of the add-on are you using? Firefox or Chrome?

**Comment by SirLouen** [comment]
Wordpress v 4.9.6 (Self-maintained not wordpress.com)
Chrome:  66.0.3359.181
Addon: 1.0.37

Another message I've seen:
> LanguageTool tracking: https://4p.marketing, error on checkText - get selection: undefined, undefined

**Comment by danielnaber** [comment]
@jaumeortola Does my test account at riuraueditors.cat still exist? I cannot log in as "daniel" anymore.

**Comment by SirLouen** [comment]
@danielnaber i've sent to your email some credentials for testing purpose

**Comment by danielnaber** [comment]
My previous fix worked only with WordPress running in English. It's fixed now, the new Chrome version will be online in an hour, currently you need to uninstall and re-install the add-on to make sure you get the update (1.0.38). Firefox will follow in a few days.

**Comment by SirLouen** [comment]
Great, now it's solved
