### ISSUE TITLE
Use with self-hosted languagetool instance

### ISSUE THREAD

**Issue by bonanza123** [languagetool-org/languagetool-browser-addon#217]
Is it generally possible to use this extension with a self-hosted languagetool instance?
If so, it would be great to have an option in the addon which can configure the server to be used (still defaulting to languagetool.org server).

**Comment by danielnaber** [comment]
Just visit the add-on's configuration dialog and set the server there.

**Comment by bonanza123** [comment]
Ahh sorry for not checking that.
But I was confused with the privacy notification that is shown upon first click:

> This extension will check your text by sending it to https://languagetool.org over an encrypted connection. Your text will not be stored. For details, see our privacy policy.

and directly removed the addon again. Maybe this option could be mentioned there as well?
