### ISSUE TITLE
Please update add-on for firefox to 1.0.35

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [languagetool-org/languagetool-browser-addon#221]
At present, the [add-on for firefox](https://addons.mozilla.org/en-US/firefox/addon/languagetool) is still 1.0.34.
Customized languagetool API server doesn't work, while the 1.0.35 version in chrome webstore works well.
The 1.0.35 version is labeled 3 months ago, is there any reason not to publish it on firefox?

**Comment by danielnaber** [comment]
There are no significant changes in 1.0.35 - what exactly doesn't work about using your own server with the Firefox add-on?

**Comment by Alkaid-Benetnash** [comment]
From my own languagetool server, I can see request is processed and replied correctly, while the extension complains 'Network Error'.
From debug console, I guess the reason is
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://x.x.x.x:xxxx/languagetool/v2/check. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

I tried and found even 1.0.35 won't work. I still haven't found a solution.

**Comment by danielnaber** [comment]
You need to start the server with `--allow-origin "*"` as a parameter.

**Comment by Alkaid-Benetnash** [comment]
Thanks, it works now. Because I used to use chrome with this addon and everything works fine, I didn't doubt about server configuration.
