### ISSUE TITLE
Suggested correction isn't applied in Gmail with Firefox add-on

### ISSUE THREAD

**Issue by sojusnik** [languagetool-org/languagetool-browser-addon#228]
The LanguageTool Firefox add-on doesn't apply the suggested correction in Gmail.

To reproduce this, open the [new Gmail interface](https://mail.google.com/mail/u/0/#inbox) and begin to write a new mail with spelling mistakes. Then click on the LanguageTool icon in the toolbar of Firefox, wait for the pop-up to appear and click on one of the suggested corrections, that normally are highlighted as yellow. After disappearing for one second, the pop-up reappears again with the same suggested corrections.

It seems to work on other sites though, at least on GitHub.

Happens on Firefox 61.0.1 on Ubuntu 18.04 with version 1.0.39 of the LanguageTool Firefox add-on.

**Comment by danielnaber** [comment]
Thanks for the report. I cannot reproduce it, though. I'm using Firefox 61.0.1 on Ubuntu 16.04. Could you send a screenshot? I'm also not sure what you mean by "new" Gmail interface, my interface hasn't changed recently.

**Comment by sojusnik** [comment]
This is the [new interface](https://www.theverge.com/2018/4/25/17277360/gmail-redesign-live-features-google-update) I'm speaking of. You should already have it. If not, then go to the [settings cog](https://cdn.vox-cdn.com/thumbor/mDzCNRWy-fbI3OjPvrN7arTf8Ic=/0x0:969x450/920x0/filters:focal(0x0:969x450)/cdn.vox-cdn.com/uploads/chorus_asset/file/10716697/2018_04_25_10_58_27.png) and try it out.

And here's a video of the whole process. May it be of help to you:
![languagetool](https://user-images.githubusercontent.com/1245718/43070361-eee4f396-8e6f-11e8-865e-6557bc9dfa6e.gif)

**Comment by danielnaber** [comment]
Thanks for the video. The thing is, I still cannot reproduce this using the "new" Gmail. Could this be caused by the other add-ons you're using? Could you turn them off as a test?

**Comment by danielnaber** [comment]
As discussed, cannot reproduce and no further feedback.

**Comment by sojusnik** [comment]
I've deactivated all my add-ons and restarted Firefox, but it didn't help.

It still happens on Firefox 62 on Ubuntu 18.04.

**Comment by sojusnik** [comment]
This issue persists on Firefox 63 and Ubuntu 18.10.

**Comment by sojusnik** [comment]
@danielnaber This issue persists on Firefox 63 and Ubuntu 18.10.

**Comment by danielnaber** [comment]
The new add-on (https://chrome.google.com/webstore/detail/languagetool-grammar-and/oldceeleldhonbafppcapldpdifcinji) will soon (in 2-3 weeks) also be available for Firefox, it should fix most of the issues of the old add-on.
