### ISSUE TITLE
LT rewrite (LT 2.x) repo.

### ISSUE THREAD

**Issue by Piter432** [languagetool-org/languagetool-browser-addon#231]
Where is the repo of rewritten LT? The extension is updating quite frequently, but I don't know **what** is changing and **I need** to report the bug(s) somewhere if I found it/them, but I don't know where the repo is 😕

**Comment by danielnaber** [comment]
The new repo is not public, but feel free to report issues in this repo.

**Comment by leonidasv** [comment]
@danielnaber What's the license for the 2.x extension? Is there any plans to release it under LGPL?

**Comment by danielnaber** [comment]
@leonidasv Sorry, the new version isn't Open Source.
