### ISSUE TITLE
please add support for thunderbird 

### ISSUE THREAD

**Issue by Mannshoch** [languagetool-org/languagetool-browser-addon#236]
This add-on is great. Please add also a thunderbird add-on with the same possibilities.

**Comment by danielnaber** [comment]
There's already an old add-on but it's not really maintained a lot: https://addons.thunderbird.net/de/thunderbird/addon/grammar-checker/ - any contributions are welcome.

**Comment by baarsrj** [comment]
Do we know where the compatibility issues are? Just in the version numbers in the metadata, in the interface to Thundderbird, or the inteface to LT?
Might be worth investigating if we do not know.

**Comment by Mannshoch** [comment]
https://github.com/nuald/thb-gramchecker seems the repository for that.

**Comment by baarsrj** [comment]
Yes, But I am not a programmer....

**Comment by ilario** [comment]
The *Grammar Checker* extension Github repository disappeared, its code can still be found in [some forks](https://github.com/IGLOU-EU/thb-gramchecker). Anyway, it is not compatible with recent Thunderbird versions. So an alternative is really needed now.

I installed the LT-browser-addon XPI file on Thunderbird, it looks good, but it does not try to correct any text in the email body.

**Comment by danielnaber** [comment]
A new Thunderbird add-on (still waiting to be reviewed) is now available at https://addons.thunderbird.net/thunderbird/addon/grammar-and-spell-checker/
