### ISSUE TITLE
cannot check text confirm privacy first

### ISSUE THREAD

**Issue by icf20** [languagetool-org/languagetool-browser-addon#242]
![image](https://user-images.githubusercontent.com/17784575/58047744-25e36780-7b49-11e9-9f64-e2e65270af47.png)

ok i suppose yet the chrome extension dont have any option to accept the policy

**Comment by danielnaber** [comment]
Have you tried clicking in the icon? A page should appear where you can confirm. If that doesn't work, which version of Chrome do you use? Does reinstalling the extension help?

**Comment by icf20** [comment]
> Have you tried clicking in the icon?

it redirects to https://languagetoolplus.com/webextension/install

**Comment by danielnaber** [comment]
> it redirects to https://languagetoolplus.com/webextension/install

Exactly - and that page should you the confirmation popup. If it doesn't, please send a screenshot of what you see and the version of Chrome you're using, plus whether you're using any other add-ons.

**Comment by icf20** [comment]
> Exactly

more like no i go to a .org domain then to chrome webstore if you think i co and accept a policy from a new domain just because you are doing this wrong
