### ISSUE TITLE
line-height in textarea is changed with an animation

### ISSUE THREAD

**Issue by Mte90** [languagetool-org/languagetool-browser-addon#243]
This is creating issues on using the extension on website like https://wordpress.org/support/plugin/polylang/ where in the textarea the text is moving and is impossible to read it.
![immagine](https://user-images.githubusercontent.com/403283/58699622-3643df80-839e-11e9-8008-aefc78c188d2.png)

**Comment by tiff** [comment]
@Mte90 many thanks. Looking into it now.

**Comment by tiff** [comment]
@Mte90 We're unable to reproduce this. Which browser are you using? Do you have other browser extensions installed? Thanks in advance.

**Comment by Mte90** [comment]
I am using firefox and yes I have different extension installed.
I saw that put a domain on whitelist fix the issue but I cannot use your extension.

**Comment by tiff** [comment]
Can you provide us a list of other extensions you have installed (screenshot of "about:addons")? You can either post this screenshot here or send it to `feedback [at] languagetool.org`.

**Comment by Mte90** [comment]
![Screenshot_20190531_125606](https://user-images.githubusercontent.com/403283/58701541-896c6100-83a3-11e9-9a1e-e47056192dc2.png)
![Screenshot_20190531_125618](https://user-images.githubusercontent.com/403283/58701542-896c6100-83a3-11e9-8ed9-da7c2d1b262c.png)

**Comment by danielnaber** [comment]
Cannot reproduce under Ubuntu with Firefox 68 (beta) and LT add-on 2.1.14

**Comment by tiff** [comment]
I'm also still not able to reproduce this but might have found the issue why this is happening. A fix will be rolled out soon.

**Comment by Mte90** [comment]
I am still facing this problem :-(

**Comment by tiff** [comment]
Sorry. We are currently preparing a new release where this *might* be fixed. You can disable checking on the corresponding website by clicking on the "LT" icon in the toolbar.

**Comment by tiff** [comment]
Update: Firefox has received a new version of our plugin. It will take until mid July until it's rolled out because they're currently making some significant changes to their addons platform.

**Comment by tiff** [comment]
@Mte90 new version (2.2.0) has been released. Please check if you received it already and whether it is fixed.

**Comment by Mte90** [comment]
confirmed that now is working :-)

**Comment by tiff** [comment]
BTW we now know where this came from and how to reproduce: the default font settings of Firefox were changed (for me it started happen when I changed the minimum font size)

**Comment by Mte90** [comment]
I am getting the same issues on the Reddit chat, the `line-height` change until to 0.1px but if remove that proprierty starts again.

**Comment by tiff** [comment]
Thanks. Looking into it now.

**Comment by tiff** [comment]
Happens because Reddit animates "line-height" through a `transition: all`. We calculate the line-height by reading it via computed style (`getComputedStyle`). This method behaves differently on Firefox and Chrome:
> During CSS transitions, getComputedStyle returns the original property value in Firefox, but the final property value in WebKit.

Source: https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

We have prepared a fix that will be part of the next release (2-3 weeks).
