### ISSUE TITLE
Add-on does not work in LibreOffice 6.3.3.1 on Ubuntu 19.10

### ISSUE THREAD

**Issue by Vladislavuz** [languagetool-org/languagetool-browser-addon#245]
![изображение](https://user-images.githubusercontent.com/30505454/68070691-79a5de00-fd82-11e9-8a33-28e024f323c8.png)
![изображение](https://user-images.githubusercontent.com/30505454/68070698-8b878100-fd82-11e9-8b09-43b94a4e6c34.png)

**Comment by danielnaber** [comment]
Please see "On Ubuntu" on this page: https://languagetool.org/issues
