### ISSUE TITLE
Could you open-source new addon?

### ISSUE THREAD

**Issue by ertugrulcetin** [languagetool-org/languagetool-browser-addon#247]
@danielnaber @tiff  That would be great if you could open source the new addon :)

**Comment by iMonZ** [comment]
LanguageTool should remove the line at the bottom of their website: “© 2021 LanguageTooler GmbH – We ♥ Open Source”
This is a shame for the Open-source community

**Comment by desk7** [comment]
Any news?

**Comment by marcoagpinto** [comment]
Like Daniel told many times: the add-on is developed with paid work, so there are no plans to open-source it.

**Comment by gojo-limitless** [comment]
> Like Daniel told many times: the add-on is developed with paid work, so there are no plans to open-source it.

One of the major reasons I started using LanguageTool in 2018-19 was its open-source browser extension. It is disappointing to learn about this change (surprisingly now, when I am trying to share good things about my experience with our readers).

While I respect the change, was there any communication to us users regarding this? The above reply does not convince me.

I would appreciate a detailed take on this.

**Comment by Splarkszter** [comment]
> the add-on is developed with paid work

Aren't the donation fueled FLOSS projects paid work too???

This is laughable, I'm never giving money to this company ever again.
