### ISSUE TITLE
LT won't stay active on Facebook

### ISSUE THREAD

**Issue by Taf56** [languagetool-org/languagetool-browser-addon#248]
I've noticed this recently. LT on Facebook. Lt] fails and shows a red exclamation mark. Clicking on these turns it back on, but only for that one post. It then reverts to a red exclamation point.

(https://user-images.githubusercontent.com/68111025/87152127-06f3e780-c2ad-11ea-8a4c-23413c4a9c55.jpg)

**Comment by danielnaber** [comment]
Could you use the "Send feedback" link in the add-on? This way we'll get useful information like browser and add-on version.

**Comment by Taf56** [comment]
Done...

**Comment by Taf56** [comment]
Reinstalled, same problem. And it's only apparent on Facebook. And now the red exclamation mark is often replaced by a red dot.

**Comment by danielnaber** [comment]
Which other add-ons do you have installed? Is it reproducible, i.e. does it happen every time?

**Comment by Taf56** [comment]
I also have Adblock Plus and FB Purity add-ons installed. The error happens at all times I use Facebook, even after clearing cookies and refreshing Firefox (and therefore having to reinstall the 3 add-ons).

**Comment by Taf56** [comment]
I just noticed that when I turn on the (long-used) add-on "F.B - Purity Cleans Up Facebook (WX)" The problem starts. So it must be an interaction with its security settings and LT. I have informed the author and hopefully a solution will be found.

**Comment by Taf56** [comment]
Now it doesn't even try to appear within Facebook with Facebook Purity active. Not even a red exclamation mark or red dot.  :-(

**Comment by danielnaber** [comment]
I'm closing old issues, assuming they have been fixed now. Feel free to re-open if the problem still occurs.
