### ISSUE TITLE
Unable to disable on localhost

### ISSUE THREAD

**Issue by aurovrata** [languagetool-org/languagetool-browser-addon#249]
I have been trying to disable the addon for websites I develop on my localhost domain as it interferes with the HTML structure of the page making it a pain to analyse.... however the disable by domain features complains each time I enter 'http:localhost/' that it is not a valid domain.

**Comment by danielnaber** [comment]
Could you try just adding `localhost`? We'll try to improve the UI so that this is less confusing.

**Comment by aurovrata** [comment]
yes, that worked!  Thanks Daniel for a sooper tool!
