### ISSUE TITLE
Applying suggestions might not work when quoted text is ignored

### ISSUE THREAD

**Issue by gulp21** [languagetool-org/languagetool-browser-addon#25]
Hi,
\> Some Text.
This is a example where applying the suggestion does not work. It happens because the context information reported back by the LT server is wrong, because LT does not know about the quoted text which has been ignored.

**Comment by danielnaber** [comment]
Also affects the WebExtensions version. Possible solutions:
* replace lines with as many spaces as the original text (requires the whitespace rule to be disabled)
* send annotated text to the server with quoted lines annotated as "markup" and thus ignored - needs support on the server side first

**Comment by danielnaber** [comment]
Fixed, with the "replace by spaces" hack (which requires us to disable `WHITESPACE_RULE`).
