### ISSUE TITLE
Doesn't work on Google Docs in pageless mode

### ISSUE THREAD

**Issue by ShadeTDW** [languagetool-org/languagetool-browser-addon#264]
It's in the title. _(To enable pageless mode: first, click **File** Then, click **Page setup** and after that, it's easy to see what to do next)_
![Screenshot](https://user-images.githubusercontent.com/105473687/201509051-401806ab-7118-48bc-a09a-4d3973db509b.png)

**Comment by danielnaber** [comment]
This should be fixed with the latest version.
