### ISSUE TITLE
Thunderbird Language check only when sending

### ISSUE THREAD

**Issue by stefanwerfling** [languagetool-org/languagetool-browser-addon#267]
It would be nice if a language test only took place when the "Send" button was pressed.

Advantage:
a) It would appeal to people who find the underlining annoying and want to finish their email first.

b) Fewer queries to the server when writing the e-mail, since the query is only sent to the server at the end (server load is reduced, traffic is less)

**Comment by danielnaber** [comment]
Well, underlining the errors is very core to the idea of LT. Also, the add-on is actually the same as the one used for the browser, so it would mean to deviate from that. I don't think we're going to implement this, sorry.
