### ISSUE TITLE
Chatzilla support

### ISSUE THREAD

**Issue by milekpl** [languagetool-org/languagetool-browser-addon#27]
From an issue languagetool/#115 reported by @x-a-n-a-x: 

LanguageTool works fine in Firefox thanks to the following add-on: https://github.com/languagetool-org/languagetool-browser-addon

But this add-on doesn't work with ChatZilla (the IRC client for Firefox): http://chatzilla.hacksrus.com/

I don't know if it's possible but it would be great to have a LanguageTool plugin for ChatZilla, to correct errors before sending a sentence to an IRC channel.

**Comment by danielnaber** [comment]
Our add-on works for the web, but Chatzilla itself seems to be an add-on and not a web page? Then it's up to Chatzilla to add support for LanguageTool.
