### ISSUE TITLE
LanguageTool does not work in Thunderbird for macOS

### ISSUE THREAD

**Issue by vaelu** [languagetool-org/languagetool-browser-addon#277]
I recently switched from my Windows to macOS and installed Thunderbird there. However, the LanguageTool extension does not work. I can see it in the top right, so it's installed, but it does not check the text.
![image](https://github.com/user-attachments/assets/286668e7-caf2-4b19-9a7b-0c6494b104b9)

**Comment by danielnaber** [comment]
Are you sure you installed it from https://addons.thunderbird.net/thunderbird/addon/grammar-and-spell-checker/? The screenshot mentions "This website", so it looks you installed the browser extension instead of the Thunderbird one?

**Comment by vaelu** [comment]
@danielnaber Yes, I installed it from there. Just reinstalled it again but it doesn't work.

**Comment by danielnaber** [comment]
Which version of TB do you use? Do you write HTML or plain text email, does it fail for both types? Also, could you send a larger screenshot that also shows some part of the email text that doesn't get checked?

**Comment by vaelu** [comment]
My TB version is 115.12.2. It happens in both email types, HTML and plain text.
![image](https://github.com/user-attachments/assets/1a36eb50-3add-4a87-b6e6-8c0d3d3b56f9)

**Comment by danielnaber** [comment]
Please make sure you're installing the add-on from within TB, i.e. clicking the cog wheel icon, then "Add-ons and Themes". If that doesn't help, I'm running out of ideas.

**Comment by vaelu** [comment]
@danielnaber I installed it directly within TB. Do you have a macOS test device, or do you know someone in the community which is using TB with LanguageTool on macOS? I would be interested in other macOS users, since I don't think that this happens only to me.

**Comment by danielnaber** [comment]
I can ask a colleague on Monday. Until then, can you open Tools -> Developer Tools and see what the output of  `navigator.userAgent`  in the console is?

![tools](https://github.com/user-attachments/assets/9488fdf8-989e-46d7-8e50-28d5f5a48a8d)

**Comment by vaelu** [comment]
@danielnaber The output is "Thunderbird".
![image](https://github.com/user-attachments/assets/5a34a981-3090-4bdc-a262-72654c96a2b9)

**Comment by danielnaber** [comment]
> The output is "Thunderbird".

That's the issue. We expect "Thunderbird/" followed by a version number. Maybe you or an add-on manually modified the user agent in the past. If you reset it (should be possible in TB's advanced config dialog), LT should start working again.

**Comment by vaelu** [comment]
@danielnaber Oh, you are right. To be honest, I don't remember exactly why I did this, but resetting the user agent fixed the problem.
