### ISSUE TITLE
Strange cursor for "Add word to dictionary"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-browser-addon#29]
The `.addword` CSS style has a `e-resize` cursor. I find that a bit confusing. I think the `+` should itself be a part of the link and have the standard cursor for links.

**Comment by mabre** [comment]
I think my original idea was that making the ``+`` part of the link makes it too easy to add a word to the dictionary accidentally. The ``e-resize`` cursor points into the direction the user has to move the mouse.

**Comment by danielnaber** [comment]
Closing, as new development now happens in the WebExtensions version and it's not affected by this.
