### ISSUE TITLE
Adding new languages and update to LT 2.6 version

### ISSUE THREAD

**Issue by thangamani-arun** [languagetool-org/languagetool-browser-addon#33]
Hi,

I woulkd like to contribute and update add-on to have LT V2.6.
Also new languages are missing in the add-on. 
I would like to contribute for the same.

FYI, I am able to build .xpi from the source code. 
But I am unable to include the latest language code "ta-IN".

Suggest me.

Thanks in Advance
--Arun

**Comment by mabre** [comment]
I think the only thing which has to be done is adding the language code to ``package.json``.
