### ISSUE TITLE
cfx test fails

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-browser-addon#38]
`cfx test` fails for me:

	Using binary at '/usr/bin/firefox'.
	Using profile at '/tmp/tmpmR_HXP.mozrunner'.
	Running tests on Firefox 36.0.1/Gecko 36.0.1 ({ec8030f7-c20a-464f-9b0e-13a3a9e97384}) under linux/x86_64.
	console.warn: languagetoolfx: Plural form unknown for locale "null"
	.JavaScript error: resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///tmp/tmpmR_HXP.mozrunner/extensions/jid1-j3KiX1n7UXrjxQ@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/context-menu.js, line 690: TypeError: messageManager is undefined
	JavaScript error: resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///tmp/tmpmR_HXP.mozrunner/extensions/jid1-j3KiX1n7UXrjxQ@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/context-menu.js, line 690: TypeError: messageManager is undefined
	console.log: languagetoolfx: [JavaScript Error: "TypeError: messageManager is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///tmp/tmpmR_HXP.mozrunner/extensions/jid1-j3KiX1n7UXrjxQ@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/context-menu.js" line: 690}]
	console.log: languagetoolfx: [JavaScript Error: "TypeError: messageManager is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///tmp/tmpmR_HXP.mozrunner/extensions/jid1-j3KiX1n7UXrjxQ@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/context-menu.js" line: 690}]
	console.error: languagetoolfx: 
	  warnings and/or errors were logged.

	1 of 2 tests passed.
	Total time: 2.608040 seconds
	Program terminated unsuccessfully.

**Comment by lidel** [comment]
I have the same problem: https://travis-ci.org/lidel/ipfs-firefox-addon/builds/56878819
Seems that there is a bug in SDK 1.17: https://bugzilla.mozilla.org/show_bug.cgi?id=1103385

**Comment by danielnaber** [comment]
Closing, as in the future we'll be using WebExtensions anyway.
