### ISSUE TITLE
Options from Firefox version in Chrome version.

### ISSUE THREAD

**Issue by Piter432** [languagetool-org/languagetool-browser-addon#40]
There's almost no settings in Chrome version of LanguageTool, except its API server URL. I suggest to “import” the setting to Chrome version from Firefox version, especially the “Language” and “Native language” options, if it's possible.

**Comment by danielnaber** [comment]
We're aware of that but our resources are very limited, so pull requests are welcome.

**Comment by danielnaber** [comment]
This is done now, except for "language", which was never really used anyway (only for extremely short texts, to replace the automatic detection). It's not yet uploaded to the store, but I'm closing this issue.
