### ISSUE TITLE
Check on form field focus (auto check)

### ISSUE THREAD

**Issue by travischoma** [languagetool-org/languagetool-browser-addon#41]
Wanted to check if there are any plans to trigger a check when focusing or typing in a form field?

**Comment by danielnaber** [comment]
I'm not sure if that makes sense as long as we need to display a pop up to show the results. Underlining errors is not so easy, but at https://bugzilla.mozilla.org/show_bug.cgi?id=1140402 we're trying to make it work.

**Comment by travischoma** [comment]
Thanks for the quick reply. I can imagine it's not easy. Grammarly does it but I'm not a big fan of Grammarly because they don't trigger JS events when they modify the input, so it's difficult to reliably save their modifications in an event based way. So I'm looking for an alternative. LanguageTool look svery promising and I like that it's open. But having to click the icon in the toolbar to trigger the check vs tabbing through a bunch of fields adds a lot of friction UX wise.

**Comment by danielnaber** [comment]
Well, at least we have a shortcut (`Ctrl+Shift+Return`) that works in most cases and that I use all the time.

**Comment by danielnaber** [comment]
Maybe a compromise could be to run the check automatically in the background and show the number of errors next to the textarea. Clicking on that number would open the popup. This way we don't have to manipulate the DOM of the textarea itself (as for underlining errors), it's enough to inject a small marker with the number of errors. This should be more robust.

**Comment by danielnaber** [comment]
See #98 instead
