### ISSUE TITLE
Palemoon compatibility

### ISSUE THREAD

**Issue by sergeevabc** [languagetool-org/languagetool-browser-addon#43]
Could you be so kind to make LanguageTool extension compatible with Firefox’s fork called [Palemoon](https://www.palemoon.org/)?

**Comment by danielnaber** [comment]
I'm not sure what's needed for that. Pull requests are welcome.

**Comment by danielnaber** [comment]
Closing, as there was no further feedback.

**Comment by sergeevabc** [comment]
Oh, it’s so sad.
