### ISSUE TITLE
LanguageTool for Opera

### ISSUE THREAD

**Issue by shwetank** [languagetool-org/languagetool-browser-addon#44]
Opera is based on the same extensions model as chrome. It would be great if this extension (the chrome version, not the firefox one) is submitted to the [opera addons site](https://addons.opera.com), so that opera users also have an easy way to use the extension. 

You could literally just submit the same .crx file that you have for chrome, as the opera addons store accepts chrome .crx files as well.

**Comment by danielnaber** [comment]
Sounds like it makes more sense the other way round: https://addons.opera.com/en/extensions/details/download-chrome-extension-9/  - maintaining the same software in yet another "store" doesn't sound like fun.
