### ISSUE TITLE
Add entry to context menu

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-browser-addon#50]
- Check selected text (if any)
- Check text field (if inside text field)

**Comment by danielnaber** [comment]
Seems to be impossible to call the popup from a context menu:

* http://stackoverflow.com/questions/17851700/how-to-open-the-default-popup-from-context-menu-in-a-chrome-extension
* http://stackoverflow.com/questions/10479679/how-can-i-open-my-extensions-pop-up-with-javascript

**Comment by danielnaber** [comment]
Will work starting with version 0.9.3 in Chromium, for Chrome it seems we have to wait for https://bugs.chromium.org/p/chromium/issues/detail?id=436489

**Comment by danielnaber** [comment]
The API is supposed to be added to Firefox 57 (https://bugzilla.mozilla.org/show_bug.cgi?id=1341126), to be released in November.

**Comment by olehmelnyk** [comment]
Any chance to make it work like a Grammarly extension - right inside a textarea?

**Comment by danielnaber** [comment]
> Any chance to make it work like a Grammarly extension - right inside a textarea?

There are no short-term plans to work on this, but contributions are welcome.

**Comment by lidel** [comment]
FYI https://bugzilla.mozilla.org/show_bug.cgi?id=1341126  is  marked as RESOLVED FIXED in Firefox 57, which will be released next week 👍
