### ISSUE TITLE
Migrate Firefox add-on to WebExtension

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-browser-addon#51]
Here's the plan:

- [x] when FF 48 is released, publish WebExtension at addons.mozilla.org and wait for feedback
- [x] when the new extension is tested and FF 48 is released, link it on languagetool.org instead of LanuageToolFx
- [x] adapt description of LanuageToolFx at addons.mozilla.org marking it as deprecated
- [ ] ~~have a final update of LanuageToolFx that directs users to the new add-on (code already prepared)~~ - does not work, I get 'Add-ons built with "cfx" are no longer accepted' on http://addons.mozilla.org
- [ ] ~~hide LanuageToolFx at addons.mozilla.org so that it cannot be found by search anymore~~ just hiding from search results isn't possible, I've adapted the title instead
- [x] add a tag to git before deleting the old extension's source directory
- [x] delete the translations of LanuageToolFx at transifex
- [x] completely remove LanuageToolFx from addons.mozilla.org

**Comment by Piter432** [comment]
> completely remove LanuageToolFx from addons.mozilla.org

Are you completely sure you want to do this? Don't forget about extensions signing, which requires to upload any extension to Mozilla's Add-ons for Firefox or the extension will not be installed on Firefox 47+ stable and beta (unless it's unbranded version of Firefox stable or beta), because of lack of the sign by Mozilla.

**Comment by danielnaber** [comment]
> Are you completely sure you want to do this?

This is a long-term goal, maybe years away. Some day the old extension will stop working anyway, as it accesses features not available anymore under WebExtensions (like accessing the user's personal dictionary).
