### ISSUE TITLE
Opening and closing quote problem (for now on Chrome).

### ISSUE THREAD

**Issue by Piter432** [languagetool-org/languagetool-browser-addon#54]
Hi.

I think there's a bug with fixing quote by LanguageTool in Chrome (didn't check on Firefox for now). The problem is simple: When I enter classic quotes (opening and closing) from my keyboard, which is `"sth"` (sth means “some text here” and it's an example for this topic) and checking the typed text in LanguageTool, LT displays a tooltip to replace the typed standard keyboard's quotes to smart quotes, which is `“”` (in Polish it's `„”`). However, after I click the opening/closing smart quote, which LT displays I can't replace the standard keyboard's closing/opening quote to smart closing/opening quote with LT, and clicking on smart closing/opening quote doesn't change anything. As far as I can remember, this bug didn't occur in one of the earlier versions (can't remember in which version everything worked fine).

Can you fix this, please? :)

**Comment by danielnaber** [comment]
Thanks for the bug report. Could you try if you can reproduce this with the latest beta at https://chrome.google.com/webstore/detail/languagetool-beta/fpgjchgblnekmbkfplkggjpaopgigngc? If so, could you please send the URL and the exact text with which this happens?

**Comment by Piter432** [comment]
Hmm, looks like everything is fine with replacing normal keyboard's quotes to smart quotes in the latest beta version.
