### ISSUE TITLE
HTML internals exposed in the error results for Ukrainian text

### ISSUE THREAD

**Issue by arysin** [languagetool-org/languagetool-browser-addon#55]
Steps to reproduce:
1. Open https://languagetool.org/ in Chrome
2. Switch to Ukrainian (observe the text errors are highlighted automatically)
3. Highlight the text
4. Press LT icon to run the check in LT extension for Chrome

Observe: first 3 errors show HTML internal code:

Знайдено ймовірну орфографічну помилку
... class="hiddenGrammarError" onkeypress="UK_SIMPLE_REPLACE---#---undefined---#---Будь-ласка - помилкове слово, виправлення: будь ла...
add to dictionary
Знайдено ймовірну орфографічну помилку
...омилкове слово, виправлення: будь ласка.---#---Будь ласка---#---Будь-ласка">Будь-ласка, вст...
add to dictionary
Знайдено ймовірну орфографічну помилку
...во, виправлення: будь ласка.---#---Будь ласка---#---Будь-ласка">Будь-ласка, вставте тутт ваш текст, аб...

This does not happen on the unchecked text, only when error formatting is already present

**Comment by danielnaber** [comment]
This is fixed now in git, can you test it? ...but the replacements don't work for me. I'll open a new issue for this.

**Comment by arysin** [comment]
Looks good now, thanks!
