### ISSUE TITLE
Where's the changelog for Firefox and Chrome versions of LanguageTool?

### ISSUE THREAD

**Issue by Piter432** [languagetool-org/languagetool-browser-addon#58]
Simple question: Where's the changelog for Firefox and Chrome versions of LanguageTool? Because on my Chrome the LanguageTool has updated, but I don't know, what are the changes for Chrome version :/

**Comment by danielnaber** [comment]
I've added a change log at https://github.com/languagetool-org/languagetool-browser-addon/blob/master/webextension/CHANGES.md

Firefox: https://github.com/languagetool-org/languagetool-browser-addon/blob/master/firefox/CHANGES
