### ISSUE TITLE
Keep manually selected language

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-browser-addon#60]
Clicking on "add to dictionary" or "ignore rule" currently loses the user-selected language setting.

More detailed description: if the language that's detected on the server-side is not correct, the user needs to fix that by selecting the correct language from the drop-down menu. The text is then re-checked with that language. Currently, if the user then does any action that triggers another re-check of the text (like accepting a suggestion for an error), the language jumps back to the original (wrong) value.

Note: we do not want to save the language selected by the user, neither for the URL nor for the domain. The user's selection should only be kept for this check. If user comes back later to the same page, the original language can be used again (because the user might use different languages).

**Comment by mathroc** [comment]
accepting a suggested fix also loses the user-selected language setting

**Comment by janschreiber** [comment]
@mathroc Can't reproduce. Which browser are you using?

**Comment by mathroc** [comment]
firefox nightly

**Comment by danielnaber** [comment]
I can reproduce with Firefox 55.
