### ISSUE TITLE
scroll problem

### ISSUE THREAD

**Issue by newsjunkie247** [languagetool-org/languagetool-browser-addon#72]
In the latest version of Nightly, the scroll bar disappears and it is not possibly to get to corrections that are lower down in the tab. It would also be great if there was a way to in pin the tab or open a window to go back and forth in longer texts as was possible in the old extension.

**Comment by danielnaber** [comment]
I can confirm with Firefox 51.0a1 (2016-08-29). Let's check back when FF51 is getting closer to release.

**Comment by danielnaber** [comment]
Related? https://bugzilla.mozilla.org/show_bug.cgi?id=1287209, https://bugzilla.mozilla.org/show_bug.cgi?id=1294442

**Comment by danielnaber** [comment]
Debugging shows this is somehow caused by `float: right` in the CSS of `.addToDict`.

**Comment by danielnaber** [comment]
It works again with FF50, so it seems FF has fixed this.
