### ISSUE TITLE
Cannot install from addons.mozilla.org

### ISSUE THREAD

**Issue by raphaelh** [languagetool-org/languagetool-browser-addon#73]
When I try to install the add-on from https://addons.mozilla.org/fr/firefox/addon/languagetool/, it fails and displays the following error:

`The add-on downloaded from this site could not be installed because it appears to be corrupt.`

Apparently it is because the signature has been changed: https://support.mozilla.org/fr/questions/1095256

**Comment by danielnaber** [comment]
I cannot reproduce this. Maybe there's some local virus checker on your system which opens the ZIP and re-packages it? What operating system are you using and which version of Firefox?

**Comment by raphaelh** [comment]
I'm on Windows 7 Pro 64 bits. I had Firefox 47 and it didn't work.
In order to answer you, I checked the version of Firefox, then Firefox noticed an update was available, and downloaded and installed it.

With Firefox 48, the problem is not longer here and LanguageTool can be installed without problem.

Thanks!
