### ISSUE TITLE
An option do disable configuration sync in Chrome

### ISSUE THREAD

**Issue by ksmigrod** [languagetool-org/languagetool-browser-addon#76]
I use LanguageTool in Chrome on my private laptop and at work.

On my laptop I keep languagetool webservice loaded via systemd.
At work we keep single languagetool virtual machine for everyone interested.

Is it possible to make server setting in Chrome extension local to specific machine just like it is in Firefox?

**Comment by danielnaber** [comment]
Firefox doesn't support sync yet (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage), i.e. what Chrome does is usually a feature, and I guess some users want it to work that way.

**Comment by danielnaber** [comment]
Sorry, I think this is too specific and not worth the effort and added complexity, so I'm closing this.
