### ISSUE TITLE
error message of the plugin should be redesigned

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool-browser-addon#77]
Currently it is just a HTML dump.
![screenshot from 2016-09-21 18-48-57](https://cloud.githubusercontent.com/assets/5239997/18718471/595ec08e-802c-11e6-87a6-e4f98be17d3f.png)

**Comment by danielnaber** [comment]
The server should be more stable now, so this error should be very rare. Pull requests welcome.

**Comment by danielnaber** [comment]
Closing as this should basically never happen and if it does, it's a server issue.
