### ISSUE TITLE
Quotes aren't ignored

### ISSUE THREAD

**Issue by sojusnik** [languagetool-org/languagetool-browser-addon#81]
Although the corresponding setting is enabled in the preferences of this add-on, quotes in [Google Inbox](http://www.google.com/inbox/), when replying to an e-mail, aren't ignored as such and are therefore checked by LanguageTool.

Observed under Firefox 49 on Ubuntu 16.04.

**Comment by danielnaber** [comment]
Quotes are detected by `>` and Google doesn't seem to use those characters. So this is out of scope for now, but pull requests are welcome.
