### ISSUE TITLE
layout bug with error class color

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-browser-addon#96]
Happened in FF only so far:

![addon-bug](https://cloud.githubusercontent.com/assets/857004/20382976/527b0152-acae-11e6-9ca8-a5bedeea16e6.png)

**Comment by danielnaber** [comment]
@bekicot Could you have a look? This seems related to https://github.com/languagetool-org/languagetool-browser-addon/pull/86

**Comment by bekicot** [comment]
@danielnaber looking on it now
