### ISSUE TITLE
Weird behaviour in Firefox 50

### ISSUE THREAD

**Issue by sojusnik** [languagetool-org/languagetool-browser-addon#99]
After the recent 1.0.7 Languagetool update, the pop-up window began to act weird, when the mouse cursor is hovered above an icon, like shown [here](https://mega.nz/#!6pJAFKgD!rEPKHSvBMRVMlnd3xMtjU_7zv3ZJuPlUCEP2iXlVZV8).

Happens on Firefox 50 under Ubuntu 16.04.

**Comment by danielnaber** [comment]
Thanks for the report, I can reproduce this. It seems FF gets confused when we replace the image with the hover variant and scrolls to the top again. Probably a FF bug. Would you be interested in reporting this to FF and/or write a workaround, e.g. a CSS-only hover?

**Comment by sojusnik** [comment]
I'm afraid, I don't really know how to do both.

**Comment by danielnaber** [comment]
I'm working on this now, a fix will hopefully be available in the next few days.

**Comment by danielnaber** [comment]
This is fixed now, but it will take 1-3 days until the new version is checked by Mozilla.

**Comment by sojusnik** [comment]
Confirming, that the bug is solved now. Thank you!
